name: App Payments Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Invocamos el estándar de seguridad centralizado
  security-compliance:
    uses: ./.github/workflows/reusable-security.yml
    with:
      min-severity: 'HIGH,CRITICAL'
    # secrets: inherit # Si necesitaras pasarle secretos de la organización

  # Solo si la seguridad pasa, procedemos al build
  build:
    needs: [security-compliance]
    runs-on: arc-runner-set
    steps:
      - run: echo "Seguridad validada. Procediendo con el Build... ✅"
