name: Check K8s Secret
on: workflow_dispatch

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: Print Secret (Masked)
        run: |
          echo "El secreto inyectado desde K8s es: $MY_K8S_TOKEN"
          # Agregamos una validación
          if [ -z "$MY_K8S_TOKEN" ]; then
            echo "Error: Secreto no encontrado"
            exit 1
          else
            echo "Secreto detectado correctamente"
          fi
