name: Simulacion de pipeline

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: arc-org-runner-set
    steps:
      - name: Revisando codigo
        run: |
          echo "Revisando sintaxis..."
  test:
    runs-on: arc-org-runner-set
    needs: lint
    steps:
      - name: Ejecutando pruebas
        run: |
          echo "Corriendo tests unitarios..."
  build:
    runs-on: arc-org-runner-set
    needs: test
    steps:
      - name: Compilacion
        run: |
          echo "Build exitoso" >> app-v1.txt
      - name: Carga artefacto
        uses: actions/upload-artifact@v4
        with:
          name: mi-artefacto
          path: app-v1.txt
