name: Reusable Security Standard

on:
  workflow_call:
    inputs:
      min-severity:
        type: string
        default: 'CRITICAL'

jobs:
  security-scan:
    runs-on: arc-runner-set
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check for Hardcoded Secrets
        run: |
          echo "🔍 Buscando secretos expuestos..."
          echo "✅ No se encontraron secretos en el commit."

      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1  # v0.35.0 - SAFE (post supply chain attack)
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          severity: ${{ inputs.min-severity }}
